### ISSUE TITLE
Problems using with bundler > 1.12

### ISSUE THREAD

**Issue by fernandes** [guard/guard-bundler#32]
I got an error using guard-bundler with version > 1.12, sorry I can't describe the problem, so I'm gonna paste some errors and be available for further investigation

gem install bundler -v 1.12.0

```ruby
○ guard                        
/opt/boxen/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:250:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
        from /opt/boxen/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:278:in `activate_bin_path'
        from /opt/boxen/rbenv/versions/2.3.1/bin/bundle:22:in `<main>'
11:29:00 - INFO - Bundling...
/opt/boxen/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:250:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
        from /opt/boxen/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:278:in `activate_bin_path'
        from /opt/boxen/rbenv/versions/2.3.1/bin/bundle:22:in `<main>'
11:29:00 - INFO - Bundle can't be installed -- Please check manually
```

gem uninstall -x bundler
gem install bundler -v 1.11.2

```ruby
○ guard
11:29:47 - INFO - Bundle already up-to-date
11:29:47 - INFO - Guard is now watching at '/Users/fernandes/src/project'
```

ps: I don't discard the possibility of being a bundler bug, I'm just in no position to judge.

thank you!

**Comment by e2** [comment]
Sure, thanks for reporting.

First, try 'bundle exec guard' instead. That should work without issues.

For debugging rubygems issues, you'll need the output of `gem env`. (You can actually put something like this into your `Guardfile`:

```ruby
Kernel.system("gem env")
```

Things are a bit tricky when using bundler/rubygems with Guard, so do ask for help, because it could be many things.

E.g. you may want to know if the `RUBYGEMS_GEMDEPS` environment is set. You may need to provide your `Gemfile` contents. If it's a gem you're developing, there might be something wrong with the gemspec file.

guard tries to use use Bundler internally if there's a Gemfile and you're not using `RUBYGEMS_GEMDEPS`.

You can also run `bundle exec guard -d` for more debugging output.

If you can create a mini-repository demonstrating the problem, I can take a quick look.

Also, thanks for reporting - because if there's anything I can do to at least make the error more "descriptive" by Guard, I'd be happy to.

**Comment by fernandes** [comment]
hey @e2 thanks for quick reply... :)

trying `bundle exec guard`

```ruby
○ gem install bundler
Fetching: bundler-1.12.3.gem (100%)
Successfully installed bundler-1.12.3
1 gem installed
○ bundle exec guard
/opt/boxen/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:250:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
        from /opt/boxen/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:278:in `activate_bin_path'
        from /opt/boxen/rbenv/versions/2.3.1/bin/bundle:22:in `<main>'
15:38:45 - INFO - Bundling...
/opt/boxen/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:250:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
        from /opt/boxen/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:278:in `activate_bin_path'
        from /opt/boxen/rbenv/versions/2.3.1/bin/bundle:22:in `<main>'
15:38:45 - INFO - Bundle can't be installed -- Please check manually
```

Same problem :/

my `gem env` on Guardfile output (running with `guard` and `bundle exec guard`) the output is the same

```ruby
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.4
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/fernandes/src/project/vendor/bundle/ruby/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/fernandes/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /opt/boxen/rbenv/versions/2.3.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/fernandes/src/project/vendor/bundle/ruby/2.3.0/bin
  - SPEC CACHE DIRECTORY: /Users/fernandes/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /opt/boxen/rbenv/versions/2.3.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/fernandes/src/project/vendor/bundle/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-ri --no-rdoc"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/fernandes/src/project/vendor/bundle/ruby/2.3.0/bin
     - /opt/boxen/rbenv/versions/2.3.1/bin
     - /opt/boxen/rbenv/libexec
     - /opt/boxen/phpenv/shims
     - /opt/boxen/phpenv/bin
     - /opt/boxen/phpenv/plugins/php-build/bin
     - bin
     - /opt/boxen/rbenv/shims
     - /opt/boxen/rbenv/bin
     - /opt/boxen/ruby-build/bin
     - /opt/boxen/phantomenv/shims
     - /opt/boxen/phantomenv/bin
     - node_modules/.bin
     - /opt/boxen/nodenv/shims
     - /opt/boxen/nodenv/bin
     - /opt/boxen/homebrew/bin
     - /opt/boxen/homebrew/sbin
     - /opt/boxen/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - /opt/X11/bin
     - /usr/local/heroku/bin
     - /Users/fernandes/.bin
/opt/boxen/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:250:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
        from /opt/boxen/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:278:in `activate_bin_path'
        from /opt/boxen/rbenv/versions/2.3.1/bin/bundle:22:in `<main>'
```

about `RUBYGEMS_GEMDEPS` (not set)

```
○ echo $RUBYGEMS_GEMDEPS

```

and last `bundle exec guard -d` output

put on this [gist](https://gist.github.com/fernandes/b1f7a9dd5ba9b5f1b3cc436fa42fc9fc) for readability

About my env, it's a rails application with _some_ gems.. Sadly it's an internal project, but I did the following

* rails new guardbundler
* Added `guard-bundler` gem
* guard init
* guard

And got the same problem, update the project on https://github.com/fernandes/guardbundler (it's just a vanilla rails app, but we can work on the same repo to figure out what is causing the bug), added you as collab.

**Comment by e2** [comment]
I couldn't get the same error, except I don't use rbenv and my setup is different.

I think you should get the same error with the following code in a file, e.g. `bundle_test.rb`

```ruby
::Bundler.with_clean_env do
  `bundle check`
end
```

and then run:

`bundle exec ruby bundle_test.rb`

You should get the same error (without even using Guard).

What does `gem list` say? And then, `gem contents bundler` ?

**Comment by fernandes** [comment]
the output is empty

```
○ bundle exec ruby bundle_test.rb
```

```
○ gem list

*** LOCAL GEMS ***

...lots of gems...
bundler (1.12.3)
...lots of gems...
```

`gem contents bundler` [gist](https://gist.github.com/fernandes/f8a56cd48a505a7ff0b7f990c6884f4d)

I'm really lost, can't evaluate, just run the commands and paste the output

**Comment by e2** [comment]
Put the `Kernel.system("gem contents bundler")` inside your `Guardfile`. Notice that your gist contains bundler gem files, but for Ruby 2.2.3, and not Ruby 2.3.1.

**Comment by e2** [comment]
For debugging purposes, you might want to temporarily rename the directory: `/opt/boxen/rbenv/versions/2.2.3/` to e.g. `/opt/boxen/rbenv/versions/2.2.3_old/`. This may help you reproduce the problem outside your app.

You may also want to try RVM instead of rbenv if you just want to get things working. It might help you work out what's wrong.

Does your `Gemfile` have a Ruby version declared in it? Do you have a `.ruby-version` file in your project?

**Comment by fernandes** [comment]
I tested on both ruby 2.2.3 and 2.3.1, both are with the same problem (tested using a `.ruby-version` file [not Gemfile]), now that my production app is running 2.3.1, I'm testing with 2.2.3 to isolate the behavior.

If I rename the folder, I have no ruby installed for 2.2.3 heheheh how should I test?

actually I use boxen on osx, so install and use rvm means a LOT of work and break the compatibility with my team, so I prefer avoid this way

before renaming I added `Kernel.system("gem contents bundler")` and it really returns no output 😮

**Comment by e2** [comment]
I thought it was an error running it on 2.2.3.

I think it's because your gem path is reset to: `/Users/fernandes/src/project/vendor/bundle/ruby/2.3.0`

Gems are expected to be installed in `GEM_PATH`. I have no idea where or what is setting that. Maybe in the bundler config in `.bundle` (sometimes created if you use the `--without` option in Bundler).

**Comment by e2** [comment]
A "workaround" would probably be to add the following to your `Guardfile`:

Kernel.system("gem install bundler") and it should install bundler into `/Users/fernandes/src/project/vendor/bundle/ruby/2.3.0`.

You're probably overwriting `GEM_PATH` environment variable instead of prepending your project's vendor/bundle path. It could be an issue with rbenv or with your rbenv setup.

**Comment by fernandes** [comment]
hummm maybe because I always use `bundle install --path vendor/bundle` to isolate projects dependencies?

your workaround worked fine!! :)

just improved to not install `bundler` gem every single time

```ruby
Open3.popen3("gem list|egrep '^bundler\s'") do |i, o|
  Kernel.system("gem install bundler") if o.read.empty?
end
```

I'm completely satisfied with this ~~workaround~~ solution, and I do really appreciate your efforts on helping me solve this.

If you'd like to keep tracking the problem, I'm available to keep moving it forward. (in meanwhile I'm gonna open a issue on rbenv and bundle [once it just appeared on v1.12.X] to solve it)

thank you! 🙇

**Comment by fernandes** [comment]
on another project the workaround didn't work, so I did

```ruby
Open3.popen3("gem contents bundler") do |i, o|
  Kernel.system("gem install bundler") if o.read.empty?
end
```

would be great to check if installed version of bundler is the same running guard, but atm this solution is ok hehehe

**Comment by e2** [comment]
`bundle install --path vendor/bundle` - you'd need to provide that if you report a bug in Bundler.

I have no idea how bundler is supposed to behave if you use the `--path` option (I never use it myself), so I don't know if the error is correct or not.

Personally, I'd just rely on gem sets handled by RVM or rbenv instead of putting things into the vendored folder. It's best just to lock to given versions and rely on Bundler to pick matching versions (which will be the same if you isolate or not).

Here, you need to install bundler manually into the vendored dir, because bundler itself is still just a gem. 

Glad you solved it :)

**Comment by trobrock** [comment]
I am running into this issue as well, although it affects not only bundler-guard but anything running bundler inside of guard. For those trying to track down what caused this it was introduced here https://github.com/bundler/bundler/commit/4222dbccad42a9ec6d3ecd9ddaa6a283f4fecbef

**Comment by fernandes** [comment]
yeah @e2 makes perfectly sense... just worried because vendored gems are a good practice on deployments (AFAIK), if something relies on bundler would broken (not sure)

@trobrock thank you very much for your comment, I commented about this issue on that commit, let's see how it evolve.

**Comment by e2** [comment]
@fernandes - I'd say that at the speed of development nowadays, on production systems it's best to lock pessimistically to patch-level versions, e.g. `foo ~> 2.3.7`. This is because if `foo ~> 2.3` is too risky due to API-level behavior changes, then locking to a specific version like `foo = 2.3.7` is a security risk.

A lock like: `foo ~> 2.3.7` allows security patches without API-level patches if a gem uses SemVer. But still, if you do that, you have to track changes in such projects and request backporting patches if needed.

E.g. if `foo <= v2.5.8` has a bug fixed in `foo v2.5.9`, then either you need to upgrade to `foo v2.5.x` or backport the patch as `foo 2.3.8`.

So if it's important, every gem is different, because they have different policies, maintainers, release cycles, etc. Sometimes even major bugs aren't released for years, forget backporting.

"Broken" also can be understood 2 ways: sometimes fixing a bug breaks bad usage somewhere else.

A vendored gem is also one that never gets any automatic bugfixes or improvements or security updates.

Personally I think it's better to experience bugs sooner and focus on processes to prevent them - instead of trying to avoid problems by "freezing" an app to ancient versions. The short term cost seems larger, but long term you'll never appreciate all the problems you were saved from.

Trust is the least expensive and that's why it's good for business. Distrust means everyone loses.

That's why I'd focus on more frequent more automatic and more reliable updates - because everyone wins long term.

**Comment by fernandes** [comment]
ohhh thank you for all your considerations, we fix versions on Gemfile and run constant bundle updates, `path` option on bundle is just to keep projects gems isolated on respective folder.. and I do completely agree if your position :)

**Comment by dsandstrom** [comment]
I had a similar problem when upgrading bundler from 1.11 to 1.12 in a Rails 5 app.
```rb
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'bundler' (>= 0.a) among 106 total gem(s) (Gem::MissingSpecError)
```
Removing `BUNDLE_PATH: vendor/bundle` from my _.bundle/config_ fixed it.
